import React, { createContext, useContext, useEffect, useState } from 'react'

type Language = 'Turkish' | 'English'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
    Turkish: {
        'app.name': 'AKADEMİKİZ',
        'nav.dashboard': 'Panel',
        'nav.learning_plan': 'Öğrenme Planı',
        'nav.diagnostic': 'Eksik Tespiti',
        'nav.tutor_chat': 'AI ile Konuş',
        'nav.tools': 'Araçlar',
        'nav.settings': 'Ayarlar',
        'nav.attendance': 'Devamsızlık Takibi',
        'nav.add_study': 'Çalışma Ekle',
        'nav.exam_analysis': 'Deneme Analizi',
        'nav.exam_prediction': 'Konu Tahmini',
        'nav.tutor': 'AI Öğretmen',
        'nav.leaderboard': 'Liderlik Tablosu',
        'nav.exam_prep': 'Sınavım Var',
        'nav.games': 'Oyunlar 🎮',
        'nav.stats': 'İstatistikler',
        'nav.more': 'Daha Fazla',
        'nav.logout': 'Çıkış',
        'dashboard.welcome': 'Hoş geldin',
        'dashboard.subtitle': 'Bugün hedeflerine ulaşmak için harika bir gün!',
        'dashboard.add_study': '+ Yeni Çalışma Ekle',
        'dashboard.completed_study': 'Tamamlanan Çalışma',
        'dashboard.total_time': 'Toplam Süre',
        'dashboard.solved_test': 'Çözülen Test',
        'dashboard.correct_answer': 'Doğru Cevap',
        'dashboard.wrong': 'Yanlış',
        'dashboard.blank': 'Boş',
        'dashboard.recent_studies': 'Son Çalışmalar',
        'dashboard.see_all': 'Tümünü Gör →',
        'dashboard.no_studies': 'Henüz çalışma kaydı yok',
        'dashboard.start_journey': 'İlk çalışmanı ekleyerek serüvenine başla.',
        'dashboard.add_now': 'Hemen Ekle',
        'dashboard.attendance_title': 'Devamsızlık Durumu',
        'dashboard.attendance_desc': 'Derslerinin katılım durumunu kontrol et ve güncelle.',
        'dashboard.open_tracker': 'Takibi Aç',
        'dashboard.quote_title': 'Günün Sözü',
        'dashboard.prediction_title': 'Konu Tahmini',
        'dashboard.prediction_desc': 'Yapay zeka performansını analiz ederek hangi konulara odaklanman gerektiğini söyler.',
        'dashboard.view_prediction': 'Tahmini Gör',
        'dashboard.today_goal': 'Bugünün Hedefi',
        'dashboard.weak_areas': 'Zayıf Alanların',
        'dashboard.last_activity': 'Son Aktivite',
        'dashboard.continue_learning': 'Öğrenmeye Devam Et',
        'dashboard.start_diagnostic': 'Eksiklerini Tespit Et',
        'dashboard.diagnostic_desc': 'Hangi konularda eksik olduğunu öğrenmek için testi başlat.',
        'dashboard.quote_of_day': 'Günün Sözü',
        'diagnostic.title': 'Eksik Tespit (Diagnostik)',
        'diagnostic.subtitle': 'Hangi seviyede ve hangi konuda olduğunu öğrenmek için bir seçim yap.',
        'diagnostic.custom_subject': 'Ders veya Bölüm Adı Yazın',
        'diagnostic.start': 'TESTİ BAŞLAT',
        'diagnostic.mode.quick': 'Hızlı',
        'diagnostic.mode.standard': 'Standart',
        'diagnostic.mode.comprehensive': 'Kapsamlı',
        'diagnostic.loading.data': 'Veriler analiz ediliyor...',
        'diagnostic.loading.ai': 'AI ile bağlantı kuruluyor...',
        'diagnostic.loading.plan': 'Kişiselleştirilmiş plan hazırlanıyor...',
        'diagnostic.result_title': 'Analiz Raporun',
        'diagnostic.mastery_map': 'Konu Hakimiyeti',
        'diagnostic.ai_guide': 'AI Rehberi',
        'diagnostic.ideal_order': 'İdeal Çalışma Sıralaması',
        'diagnostic.new_test': 'Yeni Test',
        'diagnostic.download_report': 'Raporu İndir',
        'diagnostic.feedback_error': 'Geri bildirim şu an oluşturulamadı. Lütfen daha sonra tekrar dene.',
        'diagnostic.level': 'Seviyesi',
        'stats.desc': 'Akademik ilerlemenin detaylı analizi.',
        'stats.subject_distribution': 'Ders Dağılımı',
        'stats.performance': 'Performans',
        'stats.correct': 'Doğru',
        'stats.wrong': 'Yanlış',
        'stats.sessions': 'Çalışma',
        'tools.title': 'Araçlar Merkezi',
        'tools.subtitle': 'Akademik yolculuğunda sana güç katacak tüm yardımcı araçlar ve AI asistanları burada.',
        'tools.back': 'Panele Dön',
        'tools.exam_and_analysis': 'Sınav & Performans Analizi',
        'tools.notes_and_tracking': 'Akademik Takip Aracı',
        'tools.ai_helpers': 'Yapay Zeka Asistanları',
        'tools.others': 'Ek Özellikler',
        'settings.title': 'Kullanıcı Ayarları',
        'settings.subtitle': 'Profilini ve uygulama tercihlerini yönet.',
        'settings.profile_section': 'Profil Bilgileri',
        'settings.name_label': 'Ad Soyad',
        'settings.email_label': 'E-posta Adresi',
        'settings.update_name': 'İsmi Güncelle',
        'settings.reset_password': 'Şifremi Sıfırla',
        'settings.reset_password_desc': 'Şifre sıfırlama bağlantısı e-posta adresinize gönderilir.',
        'settings.success_update': 'Bilgiler başarıyla güncellendi.',
        'settings.error_update': 'Güncelleme sırasında bir hata oluştu.',
        'exam.target': 'Hedef',
        'exam.predicted': 'Tahmini Puan',
        'common.back': 'Geri',
        'common.loading': 'Yükleniyor...',
        'common.success': 'Başarılı!',
        'common.error': 'Hata oluştu.',
        'common.save': 'Kaydet',
        'common.cancel': 'İptal',
        'common.select': 'Seçiniz',
        'common.delete': 'Sil',
        'common.add': 'Ekle',
        'common.close': 'Kapat',
        'common.anonymous': 'Anonim',
        'common.all': 'Tümü',
        'leaderboard.title': 'Liderlik Tablosu',
        'leaderboard.desc': 'En çok puan toplayan öğrenciler.',
        'leaderboard.user': 'Öğrenci',
        'leaderboard.points': 'Puan',
        'leaderboard.no_points': 'Henüz puan toplayan kimse yok.',

        'exam.rehearsal_title': 'Sınav Provası',
        'exam.rehearsal_preparing': 'Sınav kağıdı hazırlanıyor...',
        'exam.rehearsal_evaluating': 'Yapay zeka cevapları değerlendiriyor...',
        'exam.rehearsal_finish': 'Sınavı Bitir',
        'exam.rehearsal_finish_confirm': 'Sınavı bitirmek istediğine emin misin?',
        'exam.rehearsal_answered': '{count} / {total} Cevaplandı',
        'exam.rehearsal_multiple_choice': 'Çoktan Seçmeli',
        'exam.rehearsal_true_false': 'Doğru / Yanlış',
        'exam.rehearsal_open_ended': 'Açık Uçlu Sorular',
        'exam.rehearsal_open_ended_desc': 'Cevabınızı yazın, yapay zeka değerlendirecektir.',
        'exam.rehearsal_open_placeholder': 'Cevabınızı buraya yazın...',
        'exam.rehearsal_result': 'Sınav Sonucu',
        'exam.rehearsal_score_label': 'PUAN',
        'exam.rehearsal_saved': 'Sonuçların kaydedildi.',
        'exam.rehearsal_eval_oe': '📝 Açık Uçlu Sorular - Değerlendirme',
        'exam.rehearsal_eval_mc': '✅ Çoktan Seçmeli - Sonuçlar',
        'exam.rehearsal_eval_tf': '⚖️ Doğru / Yanlış - Sonuçlar',
        'exam.rehearsal_your_answer': 'Senin cevabın',
        'exam.rehearsal_correct_answer': 'Doğru cevap',
        'exam.rehearsal_sample_answer': 'Örnek cevap',
        'exam.rehearsal_back': 'Panele Dön',

        'study.list_title': 'Çalışmalarım',
        'study.filter_label': 'Derse göre filtrele',
        'study.table_subject': 'Ders',
        'study.table_topic': 'Konu',
        'study.table_duration': 'Süre',
        'study.table_date': 'Tarih',
        'study.unit_hours_short': 'sa',
        'study.no_records': 'Henüz kayıtlı çalışma yok.',
        'subject.Matematik': 'Matematik',
        'subject.Fizik': 'Fizik',
        'subject.Kimya': 'Kimya',
        'subject.Biyoloji': 'Biyoloji',
        'subject.Türkçe': 'Türkçe',
        'subject.Tarih': 'Tarih',
        'subject.Coğrafya': 'Coğrafya',
        'subject.Felsefe': 'Felsefe',
        'subject.İngilizce': 'İngilizce',
        'subject.Diğer': 'Diğer',

        'landing.hero_badge': '🚀 YKS Hazırlığında Yeni Dönem',
        'landing.hero_title': 'Hedefine Giden Yolda',
        'landing.hero_accent': 'İz Bırak.',
        'landing.hero_desc': 'Yapay zeka destekli analizler, detaylı çalışma takibi ve gelişmiş deneme analizi ile başarıya ulaşmak artık daha kolay.',
        'landing.start_now': 'Hemen Başla',
        'landing.login': 'Giriş Yap',
        'landing.register': 'Kayıt Ol',
        'landing.feature_analysis': 'Deneme Analizi',
        'landing.feature_analysis_desc': 'Eksiklerini nokta atışı tespit et.',
        'landing.feature_planning': 'Planlama',
        'landing.feature_planning_desc': 'Akıllı program ile zamanı yönet.',
        'landing.feature_ai_coach': 'AI Koç',
        'landing.feature_ai_coach_desc': 'Sana özel tavsiyeler al.',
        'landing.feature_target': 'Hedef Takip',
        'landing.feature_target_desc': 'İlerlemeyi anlık gör.',
        'landing.footer_copyright': 'Akademik İz &copy; 2026',
        'landing.footer_about': 'Hakkımızda',
        'landing.footer_privacy': 'Gizlilik',
        'landing.footer_contact': 'İletişim',
        'landing.welcome_back': 'Tekrar Hoş Geldiniz!',
        'landing.continue_desc': 'Çalışmalarınıza kaldığınız yerden devam etmek için panele gidin.',
        'landing.back_to_panel': 'Panele Dön',
        'landing.social_proof': 'öğrenci platformda parlıyor',
        'landing.how_it_works_title': 'Sistem Nasıl İşler?',
        'landing.how_it_works_subtitle': 'Sadece birkaç adımda akademik başarını kontrol altına al.',
        'landing.step1_title': 'Verilerini Gir',
        'landing.step1_desc': 'Derslerini, çalışmalarını ve deneme sonuçlarını sisteme kaydet.',
        'landing.step2_title': 'Yapay Zeka Analiz Etsin',
        'landing.step2_desc': 'AI algoritmalarımız performansını ve eksiklerini anlık olarak belirlesin.',
        'landing.step3_title': 'Gelişimini İzle',
        'landing.step3_desc': 'Detaylı raporlar ve kişiselleştirilmiş tavsiyelerle hedefine emin adımlarla yürü.',
        'landing.features_title': 'Akademik Takipte Yeni Standart.',
        'landing.features_subtitle': 'Modern arayüz ve güçlü yapay zeka entegrasyonu ile öğrenci deneyimini yeniden tasarladık.',
        'landing.ai_complete': 'AI ANALİZİ TAMAMLANDI',
        'landing.trust_ai': 'AI Powered',
        'landing.trust_secure': 'Secure (SSL)',
        'landing.trust_privacy': 'Privacy First',

        // Dashboard Extra
        'dashboard.student_fallback': 'Öğrenci',
        'dashboard.unit_hours': 'sa',
        'dashboard.table_subject': 'Ders',
        'dashboard.table_topic': 'Konu',
        'dashboard.table_duration': 'Süre',
        'dashboard.table_date': 'Tarih',
        'dashboard.quote_prefix': 'Başarı, her gün tekrarlanan küçük çabaların toplamıdır.', // Default quote

        // Auth
        'auth.login_title': 'Giriş Yap',
        'auth.login_subtitle': 'Hesabına eriş ve iz bırakmaya devam et.',
        'auth.register_title': 'Kayıt Ol',
        'auth.register_subtitle': 'Akademik serüvenine bugün başla.',
        'auth.email': 'E-posta',
        'auth.password': 'Şifre',
        'auth.display_name': 'Ad Soyad',
        'auth.display_name_placeholder': 'Örn: Ahmet',
        'auth.email_placeholder': 'ornek@email.com',
        'auth.password_placeholder': '••••••••',
        'auth.forgot_password': 'Şifremi Unuttum',
        'auth.login_button': 'Giriş Yap',
        'auth.register_button': 'Kayıt Ol',
        'auth.logging_in': 'Giriş Yapılıyor...',
        'auth.registering': 'Kayıt Yapılıyor...',
        'auth.no_account': 'Hesabın yok mu?',
        'auth.register_now': 'Hemen Kayıt Ol',
        'auth.have_account': 'Zaten hesabın var mı?',
        'auth.reset_email_sent': 'Şifre sıfırlama e-postası gönderildi! Lütfen gelen kutunu kontrol et.',
        'auth.enter_email_error': 'Lütfen e-posta adresini girin.',
        'auth.reset_password_title': 'Yeni Şifre Belirle',
        'auth.new_password': 'Yeni Şifre',
        'auth.reset_password_button': 'Şifreyi Güncelle',
        'auth.reset_password_success': 'Şifreniz başarıyla güncellendi! Giriş yapabilirsiniz.',
        'auth.error_invalid_credentials': 'E-posta veya şifre hatalı.',
        'auth.error_email_not_confirmed': 'Lütfen e-posta adresinizi onaylayın.',
        'auth.error_user_exists': 'Bu e-posta adresiyle zaten bir kullanıcı kayıtlı.',
        'auth.error_password_too_short': 'Şifre en az 6 karakter olmalıdır.',
        'auth.error_generic': 'Bir hata oluştu, lütfen tekrar dene',
        'auth.login_google': 'Google ile Giriş Yap',
        'auth.register_google': 'Google ile Kayıt Ol',

        // Legal Pages
        'legal.about_title': 'Hakkımızda',
        'legal.about_content': 'Akademik İz, öğrencilerin YKS ve diğer akademik süreçlerinde yanlarında olmak için tasarlanmış yapay zeka destekli bir takip ve analiz platformudur. Amacımız, teknolojiyi eğitimle birleştirerek başarınızı somut verilere dayalı olarak artırmaktır.',
        'legal.privacy_title': 'Gizlilik Politikası',
        'legal.privacy_content': 'Verileriniz bizim için değerlidir. Akademik İz, kişisel bilgilerinizi korumayı taahhüt eder. Toplanan veriler sadece size özel analizler ve gelişim raporları oluşturmak için kullanılır ve üçüncü taraflarla paylaşılmaz.',
        'legal.contact_title': 'İletişim',
        'legal.contact_content': 'Bize her türlü soru, görüş ve öneriniz için ulaşabilirsiniz.',
        'legal.contact_email': 'E-posta: destek@akademikiz.com',
        'legal.contact_form_name': 'Adınız',
        'legal.contact_form_msg': 'Mesajınız',
        'legal.contact_send': 'Gönder',

        // Tutor
        'tutor.title': 'AI Öğretmen',
        'tutor.desc': 'Dilediğin konuyu sor, AI senin için açıklasın ve sorularını yanıtlasın.',
        'tutor.start_msg': 'Selam! Bugün ne öğrenmek istersin? Sorularını bekliyorum.',
        'tutor.typing': 'AI Düşünüyor...',
        'tutor.placeholder': 'Mesajını yaz...',
        'tutor.send': 'Gönder',
        'tutor.error': 'Bir hata oluştu. Tekrar dene.',

        // Games Extra
        'games.watch_ad_alert': 'Reklam izlendi! +1 Hak tanımlandı. Yeni sorunuz hazır.',
        'games.ad_playing': 'Reklam izleniyor...',
        'games.you_white': 'Sen: Beyaz',
        'games.you_black': 'Sen: Siyah',

        // Games
        'games.title': 'Oyunlar & Bulmacalar',
        'games.back': '← Menüye Dön',
        'games.puzzle_title': 'Günlük Bulmaca',
        'games.puzzle_desc': 'Her gün yeni bir soru. Doğru cevapla ve',
        'games.puzzle_points': '+10 Puan kazan!',
        'games.puzzle_played': 'Bugünkü bulmacayı çözdün. Yarın tekrar gel!',
        'games.xox_title': 'XOX (Tic Tac Toe)',
        'games.xox_desc': 'Zekanı konuştur. Her 2 galibiyette',
        'games.xox_points': '+1 Puan!',
        'games.sudoku_title': 'Sudoku',
        'games.sudoku_desc': 'Sayılarla dans et. Her 2 çözümde',
        'games.sudoku_points': '+5 Puan!',
        'games.chess_title': 'Satranç',
        'games.chess_desc': 'Usta hamleler yap. Her 2 galibiyette',
        'games.chess_points': '+5 Puan!',
        'games.check_answer': 'Cevabı Kontrol Et',
        'games.watch_ad': 'Reklam İzle (Ek Hak)',
        'games.correct': 'Harika! Doğru cevap. +10 Puan eklendi.',
        'games.wrong': 'Maalesef yanlış. Doğru cevap:',
        'games.win': 'Tebrikler, Kazandın! 🎉',
        'games.lose': 'Kaybettin. Tekrar dene! 🤖',
        'games.draw': 'Berabere! 🤝',
        'games.your_turn': 'Senin Sıran',
        'games.ai_thinking': 'Yapay Zeka Düşünüyor...',
        'games.solved': 'Sudoku Çözüldü! Tebrikler. ✨',
        'games.new_game': 'Yeni Oyun',
        'games.reset': 'Sıfırla',
        'games.delete': 'Sil',
        'games.points_congrats': 'Tebrikler! {count} galibiyete ulaştın ve +{points} Puan kazandın! 🎉',

        // Study
        'study.title': 'Yeni Çalışma Seansı',
        'study.desc': 'Çalıştığın konuyla ilgili AI tarafından oluşturulan kısa bir teste girerek verimliliğini onayla.',
        'study.subject': 'Ders',
        'study.topic': 'Konu',
        'study.hours': 'Çalışma Süresi (Saat)',
        'study.generate': 'Test Oluştur ve Başla',
        'study.generating': 'AI Soruları Hazırlıyor...',
        'study.quiz_title': 'Konu Kavrama Testi',
        'study.quiz_submit': 'Testi Bitir',
        'study.result_title': 'Çalışma Sonucu',
        'study.result_pass': 'Tebrikler! {count}/5 doğru ile bu çalışmayı başarıyla tamamladın.',
        'study.result_fail': 'Maalesef {count}/5 doğru. Bu konuyu biraz daha tekrar etmelisin.',
        'study.answer_key': 'Cevap Anahtarı',
        'study.your_answer': 'Senin Cevabın',
        'study.correct_answer': 'Doğru Cevap',
        'study.new': 'Yeni Çalışma',
        'study.back': 'Ana Sayfaya Dön',

        // Analysis
        'analysis.title': 'Deneme Analizi',
        'analysis.desc': 'Netlerini gir, yapay zeka sana özel gelişim stratejisi çıkarsın.',
        'analysis.type': 'Sınav Türü',
        'analysis.subject': 'Ders',
        'analysis.correct': 'Doğru',
        'analysis.wrong': 'Yanlış',
        'analysis.empty': 'Boş',
        'analysis.analyze': 'Analiz Et',
        'analysis.analyzing': 'Analiz Yapılıyor...',
        'analysis.history': 'Geçmiş Analizler',
        'analysis.no_history': 'Henüz analiz kaydı yok.',

        // Prediction
        'prediction.title': 'Konu Başarı Tahmini',
        'prediction.desc': 'Mevcut durumunu ve hedeflerini belirt, AI hangi konularda gelişmen gerektiğini tahmin etsin.',
        'prediction.grade_label': 'Sınıf / Seviye',
        'prediction.grade_placeholder': 'Örn: 12. Sınıf Sayısal',
        'prediction.curriculum_label': 'Tamamlanan Konular / Hedefler',
        'prediction.curriculum_placeholder': 'Hangi konularda iyisin, hedefin nedir?',
        'prediction.predict': 'Tahmin Al',
        'prediction.predicting': 'Tahmin Yapılıyor...',
        'prediction.result_title': 'Yapay Zeka Tahmini',
        'prediction.history': 'Geçmiş Tahminler',

        // Attendance
        'attendance.title': 'Devamsızlık Takibi',
        'attendance.remaining': 'Kalan Hak',
        'attendance.failed': 'Kaldın!',
        'attendance.limit': 'Sınırda!',
        'attendance.add_course': 'Ders Ekle',
        'attendance.quick_add': 'Hızlı Ekle:',
        'attendance.or_type': 'Veya kendin yaz',
        'attendance.enter_name': 'Ders adı girin...',
        'attendance.no_courses': 'Henüz ders eklenmemiş.',
        'attendance.delete': 'Dersi Sil',
        'attendance.week': 'Hafta',
        'attendance.present': 'Geldi',
        'attendance.absent': 'Gelmedi',
        'attendance.undefined': 'Belirsiz',

        'exam.hub_title': 'Sınavım Var',
        'exam.hub_desc': 'Yaklaşan sınavlarını ekle ve özel program oluştur.',
        'exam.hub_add': '+ Yeni Sınav Ekle',
        'exam.hub_no_exams': 'Henüz eklenmiş bir sınavın yok.',
        'exam.hub_first_exam': 'İlk sınavını ekle',
        'exam.hub_delete_confirm': 'Bu sınavı silmek istediğine emin misin?',
        'exam.hub_target': 'Hedef',
        'exam.hub_start': 'Çalışmaya Başla',
        'exam.add_title': 'Yeni Sınav Ekle',
        'exam.field_name': 'Sınav Adı',
        'exam.field_subject': 'Ders',
        'exam.field_grade': 'Sınıf',
        'exam.field_term': 'Dönem',
        'exam.field_date': 'Tarih',
        'exam.field_target': 'Hedef Puan',
        'exam.detail_back': '← Sınav Listesine Dön',
        'exam.history_title': 'Çalışma Geçmişi',
        'exam.history_empty': 'Henüz bu sınav için çalışma yapmadın.',
        'exam.session_quiz': 'Konu Testi (Quiz)',
        'exam.session_true_false': 'Doğru / Yanlış',
        'exam.session_rehearsal': 'Sınav Provası',
        'exam.game_quiz_desc': 'Kendini test et.',
        'exam.game_tf_desc': 'Hızlı kavram tekrarı yap.',
        'exam.game_rehearsal_desc': 'Gerçek sınav deneyimi.',
        'exam.result_added': 'Puanın eklendi.',
        'exam.game_over': 'Oyun Bitti!',
    },
    English: {
        'app.name': 'AKADEMIKIZ',
        'nav.dashboard': 'Dashboard',
        'nav.learning_plan': 'Learning Plan',
        'nav.diagnostic': 'Gap Analysis',
        'nav.tutor_chat': 'Chat with AI',
        'nav.tools': 'Tools Hub',
        'nav.settings': 'Settings',
        'nav.attendance': 'Attendance Tracker',
        'nav.add_study': 'Add Study',
        'nav.exam_analysis': 'Exam Analysis',
        'nav.exam_prediction': 'Topic Prediction',
        'nav.tutor': 'AI Tutor',
        'nav.leaderboard': 'Leaderboard',
        'nav.exam_prep': 'My Exams',
        'nav.games': 'Games 🎮',
        'nav.stats': 'Statistics',
        'nav.more': 'More',
        'nav.logout': 'Logout',
        'dashboard.welcome': 'Welcome',
        'dashboard.subtitle': "Today is a great day to reach your goals!",
        'dashboard.add_study': '+ Add New Study',
        'dashboard.completed_study': 'Completed Studies',
        'dashboard.total_time': 'Total Time',
        'dashboard.solved_test': 'Tests Solved',
        'dashboard.correct_answer': 'Correct Answers',
        'dashboard.wrong': 'Wrong',
        'dashboard.blank': 'Blank',
        'dashboard.recent_studies': 'Recent Studies',
        'dashboard.see_all': 'See All →',
        'dashboard.no_studies': 'No study records yet',
        'dashboard.start_journey': 'Start your journey by adding your first study.',
        'dashboard.add_now': 'Add Now',
        'dashboard.attendance_title': 'Attendance Status',
        'dashboard.attendance_desc': 'Check and update your course attendance status.',
        'dashboard.open_tracker': 'Open Tracker',
        'dashboard.quote_title': 'Quote of the Day',
        'dashboard.prediction_title': 'Topic Prediction',
        'dashboard.prediction_desc': 'AI analyzes your performance to predict which topics you should focus on.',
        'dashboard.view_prediction': 'View Prediction',
        'dashboard.today_goal': "Today's Goal",
        'dashboard.weak_areas': 'Weak Areas',
        'dashboard.last_activity': 'Recent Activity',
        'dashboard.continue_learning': 'Continue Learning',
        'dashboard.start_diagnostic': 'Identify Your Gaps',
        'dashboard.diagnostic_desc': 'Start the test to find out which topics you need to work on.',
        'dashboard.quote_of_day': 'Quote of the Day',
        'diagnostic.title': 'Gap Analysis (Diagnostic)',
        'diagnostic.subtitle': 'Make a selection to find out your level and subject mastery.',
        'diagnostic.custom_subject': 'Enter Subject or Department',
        'diagnostic.start': 'START TEST',
        'diagnostic.mode.quick': 'Quick',
        'diagnostic.mode.standard': 'Standard',
        'diagnostic.mode.comprehensive': 'Comprehensive',
        'diagnostic.loading.data': 'Analyzing data...',
        'diagnostic.loading.ai': 'Connecting to AI...',
        'diagnostic.loading.plan': 'Preparing personalized plan...',
        'diagnostic.result_title': 'Analysis Report',
        'diagnostic.mastery_map': 'Topic Mastery',
        'diagnostic.ai_guide': 'AI Guide',
        'diagnostic.ideal_order': 'Ideal Study Order',
        'diagnostic.new_test': 'New Test',
        'diagnostic.download_report': 'Download Report',
        'diagnostic.feedback_error': 'Feedback could not be generated right now. Please try again later.',
        'diagnostic.level': 'Level',
        'stats.desc': 'Detailed analysis of your academic progress.',
        'stats.subject_distribution': 'Subject Distribution',
        'stats.performance': 'Performance',
        'stats.correct': 'Correct',
        'stats.wrong': 'Wrong',
        'stats.sessions': 'Sessions',
        'tools.title': 'Tools Hub',
        'tools.subtitle': 'All assistant tools and AI companions to empower your academic journey are here.',
        'tools.back': 'Back to Panel',
        'tools.exam_and_analysis': 'Exam & Performance Analysis',
        'tools.notes_and_tracking': 'Academic Tracker',
        'tools.ai_helpers': 'AI Assistants',
        'tools.others': 'Extra Features',
        'settings.title': 'User Settings',
        'settings.subtitle': 'Manage your profile and application preferences.',
        'settings.profile_section': 'Profile Information',
        'settings.name_label': 'Full Name',
        'settings.email_label': 'Email Address',
        'settings.update_name': 'Update Name',
        'settings.reset_password': 'Reset Password',
        'settings.reset_password_desc': 'A password reset link will be sent to your email.',
        'settings.success_update': 'Information updated successfully.',
        'settings.error_update': 'An error occurred during update.',
        'exam.target': 'Target',
        'exam.predicted': 'Predicted Score',
        'common.back': 'Back',
        'common.loading': 'Loading...',
        'common.success': 'Success!',
        'common.error': 'Error occurred.',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.select': 'Select',
        'common.delete': 'Delete',
        'common.add': 'Add',
        'common.close': 'Close',
        'common.anonymous': 'Anonymous',
        'common.all': 'All',
        'leaderboard.title': 'Leaderboard',
        'leaderboard.desc': 'Students with the highest points.',
        'leaderboard.user': 'Student',
        'leaderboard.points': 'Points',
        'leaderboard.no_points': 'No points collected yet.',

        'exam.rehearsal_title': 'Exam Rehearsal',
        'exam.rehearsal_preparing': 'Preparing exam paper...',
        'exam.rehearsal_evaluating': 'AI is evaluating answers...',
        'exam.rehearsal_finish': 'Finish Exam',
        'exam.rehearsal_finish_confirm': 'Are you sure you want to finish the exam?',
        'exam.rehearsal_answered': '{count} / {total} Answered',
        'exam.rehearsal_multiple_choice': 'Multiple Choice',
        'exam.rehearsal_true_false': 'True / False',
        'exam.rehearsal_open_ended': 'Open Ended Questions',
        'exam.rehearsal_open_ended_desc': 'Write your answer, AI will evaluate.',
        'exam.rehearsal_open_placeholder': 'Write your answer here...',
        'exam.rehearsal_result': 'Exam Result',
        'exam.rehearsal_score_label': 'SCORE',
        'exam.rehearsal_saved': 'Your results have been saved.',
        'exam.rehearsal_eval_oe': '📝 Open Ended Questions - Evaluation',
        'exam.rehearsal_eval_mc': '✅ Multiple Choice - Results',
        'exam.rehearsal_eval_tf': '⚖️ True / False - Results',
        'exam.rehearsal_your_answer': 'Your answer',
        'exam.rehearsal_correct_answer': 'Correct answer',
        'exam.rehearsal_sample_answer': 'Sample answer',
        'exam.rehearsal_back': 'Back to Panel',

        'study.list_title': 'My Studies',
        'study.filter_label': 'Filter by subject',
        'study.table_subject': 'Subject',
        'study.table_topic': 'Topic',
        'study.table_duration': 'Duration',
        'study.table_date': 'Date',
        'study.unit_hours_short': 'h',
        'study.no_records': 'No study records yet.',
        'subject.Matematik': 'Math',
        'subject.Fizik': 'Physics',
        'subject.Kimya': 'Chemistry',
        'subject.Biyoloji': 'Biology',
        'subject.Türkçe': 'Turkish',
        'subject.Tarih': 'History',
        'subject.Coğrafya': 'Geography',
        'subject.Felsefe': 'Philosophy',
        'subject.İngilizce': 'English',
        'subject.Diğer': 'Other',

        'landing.hero_badge': '🚀 New Era in YKS Preparation',
        'landing.hero_title': 'On the Road to Your Goal',
        'landing.hero_accent': 'Leave an Impression.',
        'landing.hero_desc': 'Achieving success is now easier with AI-powered analyses, detailed study tracking, and advanced trial analysis.',
        'landing.start_now': 'Start Now',
        'landing.login': 'Login',
        'landing.register': 'Register',
        'landing.feature_analysis': 'Exam Analysis',
        'landing.feature_analysis_desc': 'Identify your gaps with pinpoint accuracy.',
        'landing.feature_planning': 'Planning',
        'landing.feature_planning_desc': 'Manage your time with an intelligent schedule.',
        'landing.feature_ai_coach': 'AI Coach',
        'landing.feature_ai_coach_desc': 'Get personalized advice.',
        'landing.feature_target': 'Goal Tracking',
        'landing.feature_target_desc': 'See your progress in real-time.',
        'landing.footer_copyright': 'Akademik İz &copy; 2026',
        'landing.footer_about': 'About Us',
        'landing.footer_privacy': 'Privacy',
        'landing.footer_contact': 'Contact',
        'landing.welcome_back': 'Welcome Back!',
        'landing.continue_desc': 'Go to the dashboard to continue your studies where you left off.',
        'landing.back_to_panel': 'Back to Dashboard',
        'landing.social_proof': 'students are shining on platform',
        'landing.how_it_works_title': 'How It Works?',
        'landing.how_it_works_subtitle': 'Take control of your academic success in just a few steps.',
        'landing.step1_title': 'Enter Your Data',
        'landing.step1_desc': 'Record your courses, studies, and exam results into the system.',
        'landing.step2_title': 'AI Analyzes',
        'landing.step2_desc': 'Our AI algorithms identify your performance and gaps instantly.',
        'landing.step3_title': 'Track Your Progress',
        'landing.step3_desc': 'Walk towards your goal with confidence through detailed reports and personalized advice.',
        'landing.features_title': 'New Standard in Academic Tracking.',
        'landing.features_subtitle': 'We have redesigned the student experience with a modern interface and powerful AI integration.',
        'landing.ai_complete': 'AI ANALYSIS COMPLETED',
        'landing.trust_ai': 'AI Powered',
        'landing.trust_secure': 'Secure (SSL)',
        'landing.trust_privacy': 'Privacy First',

        // Dashboard Extra
        'dashboard.student_fallback': 'Student',
        'dashboard.unit_hours': 'hr',
        'dashboard.table_subject': 'Subject',
        'dashboard.table_topic': 'Topic',
        'dashboard.table_duration': 'Duration',
        'dashboard.table_date': 'Date',
        'dashboard.quote_prefix': 'Success is the sum of small efforts, repeated day in and day out.',

        // Auth
        'auth.login_title': 'Login',
        'auth.login_subtitle': 'Access your account and continue leaving your mark.',
        'auth.register_title': 'Sign Up',
        'auth.register_subtitle': 'Start your academic journey today.',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.display_name': 'Full Name',
        'auth.display_name_placeholder': 'e.g. John Doe',
        'auth.email_placeholder': 'example@email.com',
        'auth.password_placeholder': '••••••••',
        'auth.forgot_password': 'Forgot Password?',
        'auth.login_button': 'Login',
        'auth.register_button': 'Sign Up',
        'auth.logging_in': 'Logging in...',
        'auth.registering': 'Signing up...',
        'auth.no_account': 'No account?',
        'auth.register_now': 'Register Now',
        'auth.have_account': 'Already have an account?',
        'auth.reset_email_sent': 'Password reset email sent! Please check your inbox.',
        'auth.enter_email_error': 'Please enter your email address.',
        'auth.reset_password_title': 'Reset Your Password',
        'auth.new_password': 'New Password',
        'auth.reset_password_button': 'Update Password',
        'auth.reset_password_success': 'Your password has been updated successfully! You can now log in.',
        'auth.error_invalid_credentials': 'Invalid email or password.',
        'auth.error_email_not_confirmed': 'Please confirm your email address.',
        'auth.error_user_exists': 'A user with this email already exists.',
        'auth.error_password_too_short': 'Password should be at least 6 characters.',
        'auth.error_generic': 'An error occurred, please try again',
        'auth.login_google': 'Sign in with Google',
        'auth.register_google': 'Sign up with Google',

        // Legal Pages
        'legal.about_title': 'About Us',
        'legal.about_content': 'Akademik İz is an AI-powered tracking and analysis platform designed to support students during YKS and other academic processes. Our goal is to increase your success based on concrete data by combining technology with education.',
        'legal.privacy_title': 'Privacy Policy',
        'legal.privacy_content': 'Your data is valuable to us. Akademik İz is committed to protecting your personal information. Collected data is only used to create personalized analyses and progress reports and is not shared with third parties.',
        'legal.contact_title': 'Contact',
        'legal.contact_content': 'You can reach us for any questions, comments, or suggestions.',
        'legal.contact_email': 'Email: support@akademikiz.com',
        'legal.contact_form_name': 'Your Name',
        'legal.contact_form_msg': 'Your Message',
        'legal.contact_send': 'Send',

        // Tutor
        'tutor.title': 'AI Tutor',
        'tutor.desc': 'Ask any subject, AI will explain and answer your questions for you.',
        'tutor.start_msg': 'Hello! What do you want to learn today? I am waiting for your questions.',
        'tutor.typing': 'AI is Thinking...',
        'tutor.placeholder': 'Type your message...',
        'tutor.send': 'Send',
        'tutor.error': 'An error occurred. Try again.',

        // Games Extra
        'games.watch_ad_alert': 'Ad watched! +1 Life granted. Your new question is ready.',
        'games.ad_playing': 'Ad is playing...',
        'games.you_white': 'You: White',
        'games.you_black': 'You: Black',

        // Games
        'games.title': 'Games & Puzzles',
        'games.back': '← Back to Menu',
        'games.puzzle_title': 'Daily Puzzle',
        'games.puzzle_desc': 'A new question every day. Answer correctly and',
        'games.puzzle_points': 'win +10 Points!',
        'games.puzzle_played': "You've solved today's puzzle. Come back tomorrow!",
        'games.xox_title': 'Tic Tac Toe',
        'games.xox_desc': 'Show your intelligence. Every 2 wins',
        'games.xox_points': '+1 Point!',
        'games.sudoku_title': 'Sudoku',
        'games.sudoku_desc': 'Dance with numbers. Every 2 solutions',
        'games.sudoku_points': '+5 Points!',
        'games.chess_title': 'Chess',
        'games.chess_desc': 'Make master moves. Every 2 wins',
        'games.chess_points': '+5 Points!',
        'games.check_answer': 'Check Answer',
        'games.watch_ad': 'Watch Ad (Extra Chance)',
        'games.correct': 'Great! Correct answer. +10 Points added.',
        'games.wrong': 'Unfortunately wrong. Correct answer:',
        'games.win': 'Congratulations, You Won! 🎉',
        'games.lose': 'You Lost. Try again! 🤖',
        'games.draw': 'Draw! 🤝',
        'games.your_turn': 'Your Turn',
        'games.ai_thinking': 'AI is thinking...',
        'games.solved': 'Sudoku Solved! Congratulations. ✨',
        'games.new_game': 'New Game',
        'games.reset': 'Reset',
        'games.delete': 'Delete',
        'games.points_congrats': 'Congratulations! You reached {count} wins and earned +{points} Points! 🎉',

        // Study
        'study.title': 'New Study Session',
        'study.desc': 'Confirm your efficiency by taking a short AI-generated test on the subject you studied.',
        'study.subject': 'Subject',
        'study.topic': 'Topic',
        'study.hours': 'Study Duration (Hours)',
        'study.generate': 'Create Test & Start',
        'study.generating': 'AI is preparing questions...',
        'study.quiz_title': 'Subject Mastery Test',
        'study.quiz_submit': 'Finish Test',
        'study.result_title': 'Study Result',
        'study.result_pass': 'Congratulations! You successfully completed this study with {count}/5 correct.',
        'study.result_fail': 'Unfortunately {count}/5 correct. You should review this topic a bit more.',
        'study.answer_key': 'Answer Key',
        'study.your_answer': 'Your Answer',
        'study.correct_answer': 'Correct Answer',
        'study.new': 'New Study',
        'study.back': 'Back to Home',

        // Analysis
        'analysis.title': 'Exam Analysis',
        'analysis.desc': 'Enter your scores, and AI will create a specific development strategy for you.',
        'analysis.type': 'Exam Type',
        'analysis.subject': 'Subject',
        'analysis.correct': 'Correct',
        'analysis.wrong': 'Wrong',
        'analysis.empty': 'Empty',
        'analysis.analyze': 'Analyze',
        'analysis.analyzing': 'Analyzing...',
        'analysis.history': 'Past Analyses',
        'analysis.no_history': 'No analysis records yet.',

        // Prediction
        'prediction.title': 'Topic Success Prediction',
        'prediction.desc': 'State your current situation and goals, and AI will project which topics you should improve.',
        'prediction.grade_label': 'Grade / Level',
        'prediction.grade_placeholder': 'e.g. 12th Grade Science',
        'prediction.curriculum_label': 'Completed Topics / Goals',
        'prediction.curriculum_placeholder': 'What are you good at, what is your goal?',
        'prediction.predict': 'Get Prediction',
        'prediction.predicting': 'Predicting...',
        'prediction.result_title': 'AI Prediction',
        'prediction.history': 'Past Predictions',

        // Attendance
        'attendance.title': 'Attendance Tracker',
        'attendance.remaining': 'Remaining Limit',
        'attendance.failed': 'Failed!',
        'attendance.limit': 'On the limit!',
        'attendance.add_course': 'Add Course',
        'attendance.quick_add': 'Quick Add:',
        'attendance.or_type': 'Or type your own',
        'attendance.enter_name': 'Enter course name...',
        'attendance.no_courses': 'No courses added yet.',
        'attendance.delete': 'Delete Course',
        'attendance.week': 'Week',
        'attendance.present': 'Present',
        'attendance.absent': 'Absent',
        'attendance.undefined': 'Undefined',

        'exam.hub_title': 'I Have an Exam',
        'exam.hub_desc': 'Add your upcoming exams and create a special schedule.',
        'exam.hub_add': '+ Add New Exam',
        'exam.hub_no_exams': 'You haven\'t added any exams yet.',
        'exam.hub_first_exam': 'Add your first exam',
        'exam.hub_delete_confirm': 'Are you sure you want to delete this exam?',
        'exam.hub_target': 'Target',
        'exam.hub_start': 'Start Studying',
        'exam.add_title': 'Add New Exam',
        'exam.field_name': 'Exam Name',
        'exam.field_subject': 'Subject',
        'exam.field_grade': 'Grade',
        'exam.field_term': 'Term',
        'exam.field_date': 'Date',
        'exam.field_target': 'Target Score',
        'exam.detail_back': '← Back to Exam List',
        'exam.history_title': 'Study History',
        'exam.history_empty': 'You haven\'t studied for this exam yet.',
        'exam.session_quiz': 'Topic Quiz',
        'exam.session_true_false': 'True / False',
        'exam.session_rehearsal': 'Exam Rehearsal',
        'exam.game_quiz_desc': 'Test yourself.',
        'exam.game_tf_desc': 'Do quick concept review.',
        'exam.game_rehearsal_desc': 'Real exam experience.',
        'exam.result_added': 'Your score has been added.',
        'exam.game_over': 'Game Over!',
    }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem('app_language')
        return (saved as Language) || 'Turkish'
    })

    useEffect(() => {
        localStorage.setItem('app_language', language)
    }, [language])

    const t = (key: string): string => {
        return translations[language][key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
